<a href="https://colab.research.google.com/github/torbjorns/jupyter/blob/master/matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sys
import numpy as np

print ('Python: {}'.format(sys.version))
print ('NumPy: {}'.format(np.__version__))

Python: 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0]
NumPy: 1.18.2


In [2]:
# defining a scalar
x = 6
x

6

In [3]:
# defining a vector
x = np.array((1, 2, 3))
x

array([1, 2, 3])

In [4]:
print ('Vector Dimensions: {}'.format(x.shape))
print ('Vector Size: {}'.format(x.size))

Vector Dimensions: (3,)
Vector Size: 3


In [5]:
# defining a matrix
x = np.matrix([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
x

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [6]:
print('Matrix Dimensions: {}'.format(x.shape))
print('Matrix Size: {}'.format(x.size))

Matrix Dimensions: (3, 3)
Matrix Size: 9


In [7]:
# defining a matrix of ones
x = np.ones((3,3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])