<a href="https://colab.research.google.com/github/torbjorns/jupyter/blob/master/matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sys
import numpy as np

print ('Python: {}'.format(sys.version))
print ('NumPy: {}'.format(np.__version__))

Python: 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0]
NumPy: 1.18.2


In [2]:
# defining a scalar
x = 6
x

6

In [3]:
# defining a vector
x = np.array((1, 2, 3))
x

array([1, 2, 3])

In [4]:
print ('Vector Dimensions: {}'.format(x.shape))
print ('Vector Size: {}'.format(x.size))

Vector Dimensions: (3,)
Vector Size: 3


In [5]:
# defining a matrix
x = np.matrix([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
x

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [6]:
print('Matrix Dimensions: {}'.format(x.shape))
print('Matrix Size: {}'.format(x.size))

Matrix Dimensions: (3, 3)
Matrix Size: 9


In [7]:
# defining a matrix of ones
x = np.ones((4, 4))
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
# defining a 3D tensor
x = np.ones((3,3,3))
x

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [9]:
print('Tensor Dimensions: {}'.format(x.shape))
print('Tensor Size: {}'.format(x.size))

Tensor Dimensions: (3, 3, 3)
Tensor Size: 27


In [10]:
# indexing
A = np.ones((5,5), dtype = np.int)
print(A)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [11]:
A[0,1] = 2 # changing the value at a specific point in the index
print(A)

[[1 2 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [12]:
A[:,0] = 3 # changing the value of an entire column
print(A)

[[3 2 1 1 1]
 [3 1 1 1 1]
 [3 1 1 1 1]
 [3 1 1 1 1]
 [3 1 1 1 1]]


In [13]:
A[:,:] = 5
print(A)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [14]:
A = np.ones((3,3,3), dtype = np.int)

A[:, 0, 0] = 6
print(A)

[[[6 1 1]
  [1 1 1]
  [1 1 1]]

 [[6 1 1]
  [1 1 1]
  [1 1 1]]

 [[6 1 1]
  [1 1 1]
  [1 1 1]]]


In [15]:
# Matrix operations
A = np.matrix([[1,2], [3, 4]])
B = np.ones((2,2), dtype = np.int)

print(A)
print(B)

[[1 2]
 [3 4]]
[[1 1]
 [1 1]]


In [16]:
# Element-wise sum
C = A + B
print(C)

[[2 3]
 [4 5]]


In [17]:
# Element-wise subtraction
C = A - B
print(C)

[[0 1]
 [2 3]]


In [18]:
# Element-wise multiplication
C = A * B
print(C)

[[3 3]
 [7 7]]


In [19]:
# Matrix reshape - turning an array into matrix
A = np.array(range(9))
print(A)
A = A.reshape(3, 3)
print(A)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [20]:
# Matrix transpose
B = A.T
print(B)

[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [21]:
A = np.array(range(10))
A = A.reshape(2,5)
print(A)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [23]:
B = A.T # transpose
print(B)

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [24]:
print(A.shape)
print(B.shape)

(2, 5)
(5, 2)


In [25]:
# tensors
A = np.ones((3,3,3,3,3,3,3,3,3,3))
print(A.shape)
print(len(A.shape))
print(A.size)

(3, 3, 3, 3, 3, 3, 3, 3, 3, 3)
10
59049
